### ISSUE TITLE
[REOPENED] Regression since v2.7.7 when client charset different than server charset

### ISSUE THREAD

**Issue by robstradling** [sijms/go-ora#397]
The Client Charset option that was added in #323 is no longer working correctly since v2.7.7.

https://gist.github.com/robstradling/3bf7c340bc4479f3b3a71c58a9842657 demonstrates the regression.  Please compare the [expected result](https://gist.githubusercontent.com/robstradling/3bf7c340bc4479f3b3a71c58a9842657/raw/adeaeee91b0e02be982eac6c368f42cd74f6f3e6/output_v2.7.6.txt) (built against v2.7.6) with the [regressed result](https://gist.githubusercontent.com/robstradling/3bf7c340bc4479f3b3a71c58a9842657/raw/adeaeee91b0e02be982eac6c368f42cd74f6f3e6/output_v2.7.7.txt) (built against v2.7.7).

**Comment by sijms** [comment]
fixed in new release

**Comment by robstradling** [comment]
Thanks @sijms !

I don't see a new release tag yet, but I can confirm that commit https://github.com/sijms/go-ora/commit/26be112a77bb6773a11eee29404168bee2be118b fixes the issue for me.

**Comment by sijms** [comment]
sorry I suppose to make it yesterday but I am too busy
now I make it

**Comment by robstradling** [comment]
Hi @sijms.  v2.7.9 fixed this regression for `[]string` inputs to a PL/SQL function.  However, today I've become aware that the regression also affects `string` inputs, and this is still broken with v2.7.9.

https://gist.github.com/robstradling/f8f8c04b73af72e7f137c1eedb523d15 demonstrates the `string` input regression.  Please compare the [expected result](https://gist.githubusercontent.com/robstradling/f8f8c04b73af72e7f137c1eedb523d15/raw/78fead5f50dad5a709dd529d80de8178d8aac286/output_v2.7.6.txt) (built against v2.7.6) with the [regressed result](https://gist.githubusercontent.com/robstradling/f8f8c04b73af72e7f137c1eedb523d15/raw/78fead5f50dad5a709dd529d80de8178d8aac286/output_v2.7.7.txt) (built against v2.7.7).

The [behaviour did change](https://gist.githubusercontent.com/robstradling/f8f8c04b73af72e7f137c1eedb523d15/raw/78fead5f50dad5a709dd529d80de8178d8aac286/output_v2.7.9.txt) with v2.7.9 - it now throws a `ORA-01460: unimplemented or unreasonable conversion requested` error.

Please would you take another look?

**Comment by sijms** [comment]
sorry for late
fixed in next release v2.7.10

**Comment by robstradling** [comment]
Thanks @sijms!  Please don't feel you need to apologise.  Thanks again for creating go-ora!  :-)

I can confirm that v2.7.10 fixes the issue for me.
